### PR TITLE
Update reST usage - use includes

### PR DESCRIPTION
**Pull request by marble**

### CODE REVIEW

**Comment by marble** [comment]
### The existing exception pages are ONLY modified this way:

- Some trailing blanks removed
- The "If you encountered this error" text was replaced by an include directive.

### Start page is looking nice now

image

## New pages get filled by two includes:
So these can easily be "globally" edited
image


Source:
image

Result:
image

## What do do next

When a new exception page is created, because it didn't exist and "Edit on GitHub" was clicked, the SECOND include directive should be replaced by the actual text, so that the user can edit the skeleton right away.

**Comment by alexander-nitsche** [comment]
Hi Martin, thanks for this PR, here is my feedback:

These files i would merge as they are:

1. Documentation/Exceptions/Index.rst
2. Documentation/Index.rst
3. Documentation/Settings.cfg
4. Documentation/Sitemap.rst
5. Documentation/If-you-encounter-this-exception.rst.txt (maybe a hint of how to write reST would be nice too?)

and these files i would not merge:

1. Documentation/Report-an-exception-skeleton.rst.txt
=> will transfer it to https://github.com/TYPO3-Documentation/t3docs-wiki-migration/create as the skeleton is required in that PHP app when creating a new exception page via GitHub API.

1. Documentation/Exceptions/*.rst
=> all changes like line endings will be overwritten by next wiki => docs conversion
=> will add empty line endings removal to https://github.com/TYPO3-Documentation/t3docs-wiki-migration/convert
=> will transfer .. include:: /If-you-encounter-this-exception.rst.txt to https://github.com/TYPO3-Documentation/t3docs-wiki-migration/convert then

Greetings
Alex

**Comment by marble** [comment]
Sounds good. Yes, I understand. My PR was meant to show what the desired state would/should be. And you have better knowledge how to get there. Fine.

**Comment by alexander-nitsche** [comment]
Have merged your changes as mentioned above in PR https://github.com/TYPO3-Documentation/TYPO3CMS-Exceptions/pull/2 .

**Pull request closed without merging**
